title: <p align="center"> Santosh </p>
logo: /assets/img/logo.png

description:
   <br>  
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked with Idemia for 6 years .
  Working with Nagarro for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
